⚙️ Setting: .github directory pipeline

diff --git a/.github/workflows/cd-application.yml b/.github/workflows/cd-application.yml
--- a/.github/workflows/cd-application.yml
+++ b/.github/workflows/cd-application.yml
@@ -21,8 +21,6 @@ jobs:
     steps:
       - run: echo 'Setting constants.'
 
-  # https://github.com/google-github-actions/example-workflows/tree/main/workflows/create-cloud-deploy-release
-  # App変更: secrets.App, .github/google_cloud/skaffold.template.yaml, .github/google_cloud/clouddeploy.template.yaml
   RunGoogleCloudDeploy:
     needs: [SetGlobalConstants]
     permissions:
@@ -63,13 +61,18 @@ jobs:
           export REGION=asia-northeast1
           export APP_NAME=${{ needs.SetGlobalConstants.outputs.APP_NAME }}
 
+          # Make sure template files exist before trying to substitute them
           for template in *.template.yaml; do
-            envsubst '$PROJECT_ID $REGION $APP_NAME' < "$template" > "${template%%.*}.yaml"
+            if [ -f "$template" ]; then
+              envsubst '$PROJECT_ID $REGION $APP_NAME' < "$template" > "${template%%.*}.yaml"
+            else
+              echo "Template $template not found!"
+            fi
           done
         working-directory: .github/google_cloud
 
       - name: 'Check substituted clouddeploy.yaml'
-        run: cat clouddeploy.yaml
+        run: cat clouddeploy.yaml || echo "clouddeploy.yaml not found!"
         working-directory: .github/google_cloud
 
       - name: 'Create Cloud Deploy delivery pipeline'
@@ -80,7 +83,7 @@ jobs:
         run: gcloud deploy delivery-pipelines describe ${{ needs.SetGlobalConstants.outputs.APP_NAME }} --region asia-northeast1
 
       - name: 'Create release name'
-        run: echo "RELEASE_NAME=${{ needs.SetGlobalConstants.outputs.APP_NAME }}-${GITHUB_SHA::7}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
+        run: echo "RELEASE_NAME=${{ needs.SetGlobalConstants.outputs.APP_NAME }}-${{ github.sha::7 }}-${{ github.run_number }}" >> $GITHUB_ENV
 
       - name: 'Create Cloud Deploy release'
         id: 'release'
@@ -89,7 +92,7 @@ jobs:
           delivery_pipeline: '${{ needs.SetGlobalConstants.outputs.APP_NAME }}'
           name: '${{ env.RELEASE_NAME }}'
           region: 'asia-northeast1'
-          description: '${{ env.GITHUB_COMMIT_MSG }}'
+          description: '${{ github.event.head_commit.message }}'
           skaffold_file: '.github/google_cloud/skaffold.template.yaml'
           images: 'app=asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ needs.SetGlobalConstants.outputs.APP_NAME }}/${{ needs.SetGlobalConstants.outputs.APP_NAME }}:${{ github.sha }}'
 
